### ISSUE TITLE
AttributeError: 'gtsam.gtsam.Rot3' object has no attribute 'quaternion'

### ISSUE THREAD

**Issue by victor-velazquez-ai** [jake3991/sonar-SLAM#11]
Hello, and thanks for the great work.
After succesfully compiling the packages, and launching properly, no error. 

But as soon as running the bag I get the following error:

[ERROR] [1697454432.597592]: bad callback: <bound method Subscriber.callback of <message_filters.Subscriber object at 0x7fe39c4d99a0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 76, in callback
    self.signalMessage(msg)
  File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 58, in signalMessage
    cb(*(msg + args))
  File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 330, in add
    self.signalMessage(*msgs)
  File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 58, in signalMessage
    cb(*(msg + args))
  File "/home/PRIO-IT/victor.velazquez/slam_ws/src/sonar-SLAM/bruce_slam/src/bruce_slam/dead_reckoning.py", line 141, in callback
    self.send_odometry(vel,rot,dvl_msg.header.stamp,depth_msg.depth)
  File "/home/PRIO-IT/victor.velazquez/slam_ws/src/sonar-SLAM/bruce_slam/src/bruce_slam/dead_reckoning.py", line 267, in send_odometry
    self.publish_pose(new_keyframe)
  File "/home/PRIO-IT/victor.velazquez/slam_ws/src/sonar-SLAM/bruce_slam/src/bruce_slam/dead_reckoning.py", line 287, in publish_pose
    odom_msg.pose.pose = g2r(self.pose)
  File "/home/PRIO-IT/victor.velazquez/slam_ws/src/sonar-SLAM/bruce_slam/src/bruce_slam/utils/conversions.py", line 202, in g2r
    qw, qx, qy, qz = pose.rotation().quaternion()
AttributeError: 'gtsam.gtsam.Rot3' object has no attribute 'quaternion'

This happend to me in the two computers I tried to run the library.

Equivalently if runned offline I get same error.

Has anybody faced this issue, or know a solution?

Thanks

**Comment by jake3991** [comment]
Thanks for your interest. Could you post what version of gtsam you are using?

**Comment by victor-velazquez-ai** [comment]
very appreciated the fast response,

pip show gtsam
Name: gtsam
Version: 4.2
Summary: Georgia Tech Smoothing And Mapping library
Home-page: https://gtsam.org/
Author: Frank Dellaert et. al.
Author-email: frank.dellaert@gtsam.org
License: Simplified BSD license
Location: /usr/local/lib/python3.8/dist-packages
Requires: numpy, pyparsing

**Comment by jake3991** [comment]
I have a feeling this is GTSAM API related, I am still on a different version, see my pip show output below. Can you test using the same version I have below?


Name: gtsam
Version: 4.1.1
Summary: Georgia Tech Smoothing And Mapping library
Home-page: https://gtsam.org/
Author: Frank Dellaert et. al.
Author-email: frank.dellaert@gtsam.org
License: Simplified BSD license
Location: /home/jake/.local/lib/python3.8/site-packages
Requires: numpy, pyparsing
Required-by:

**Comment by victor-velazquez-ai** [comment]
Hello,
Downgraded to your exact version, and now is running correctly!

Thanks again,
Cheerz

**Comment by jake3991** [comment]
Great! Glad to hear it!
